version: '3'
services:
  sftpgo:
    image: drakkan/sftpgo:${SOFTWARE_VERSION_TAG}
    restart: always
    user: 0:0
    environment: 
      - SFTPGO_HTTPD__BINDINGS__0__PROXY_ALLOWED=172.0.0.0/8,192.168.0.0/16
      - SFTPGO_HTTPD__BINDINGS__0__CLIENT_IP_PROXY_HEADER=X-Real-IP
      - SFTPGO_HTTPD__BINDINGS__0__CLIENT_IP_HEADER_DEPTH=0
      - SFTPGO_FTPD__BINDINGS__0__PORT=21
      - SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_FILE=/certs/server.cert
      - SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_KEY_FILE=/certs/server.key
      - SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=$IP
      - SFTPGO_FTPD__PASSIVE_PORT_RANGE__START=50000
      - SFTPGO_FTPD__PASSIVE_PORT_RANGE__END=50100
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
      - SFTPGO_WEBDAVD__BINDINGS__0__PROXY_ALLOWED=172.0.0.0/8,192.168.0.0/16
      - SFTPGO_WEBDAVD__BINDINGS__0__CLIENT_IP_PROXY_HEADER=X-Real-IP
      - SFTPGO_WEBDAVD__BINDINGS__0__CLIENT_IP_HEADER_DEPTH=0
      - SFTPGO_SMTP__HOST=172.17.0.1
      - SFTPGO_SMTP__PORT=25
      - SFTPGO_SMTP__FROM=${HOST_DOMAIN}@vm.elestio.app
      - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=1
      - SFTPGO_DEFAULT_ADMIN_USERNAME=${ADMIN_LOGIN}
      - SFTPGO_DEFAULT_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "172.17.0.1:8080:8080"
      - "172.17.0.1:2121:21"
      - "172.17.0.1:2222:2022"
      - "172.17.0.1:10880:10080"
      - "50000-50100:50000-50100"
    volumes:
      - /root/.acme.sh/vm.elestio.app/fullchain.cer:/certs/server.cert
      - /root/.acme.sh/vm.elestio.app/vm.elestio.app.key:/certs/server.key
      - "./data:/srv/sftpgo/data"
      - "./backups:/srv/sftpgo/backups"
      - "./config:/var/lib/sftpgo"